### ISSUE TITLE
Panic when doing "loxicmd get ct"

### ISSUE THREAD

**Issue by PacketCrunch** [loxilb-io/loxilb#330]
When running 50k sessions, and doing "loxicmd get ct", the following panic logs are seen 

```
023-06-21 10:08:44 [API] Conntrack GET API called. url : /netlox/v1/config/conntrack/all
2023/06/21 10:08:58 http: panic serving 127.0.0.1:38538: write tcp 127.0.0.1:11111->127.0.0.1:38538: write: connection reset by peer
goroutine 134 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0xd72480, 0xc00363c0a0})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/loxilb-io/loxilb/api/restapi/operations.(*GetConfigConntrackAllOK).WriteResponse(0xc003612020, {0x1292080, 0xc00018e000}, {0x128d180, 0xf0d4f8})
	/root/loxilb-io/loxilb/api/restapi/operations/get_config_conntrack_all_responses.go:56 +0xa6
github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc002fcf500, {0x1292080?, 0xc00018e000}, 0xc00021c500, {0xc00358f3f0?, 0x1, 0x1}, 0xc00021c400, {0xd51ca0, 0xc003612020})
	/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x59a
github.com/loxilb-io/loxilb/api/restapi/operations.(*GetConfigConntrackAll).ServeHTTP(0xc002f17578, {0x1292080, 0xc00018e000}, 0xc00021c500)
	/root/loxilb-io/loxilb/api/restapi/operations/get_config_conntrack_all.go:63 +0x1aa
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x1292080, 0xc00018e000}, 0xc00021c500)
	/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0x59
net/http.HandlerFunc.ServeHTTP(0x418c25?, {0x1292080?, 0xc00018e000?}, 0x100?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x1292080, 0xc00018e000}, 0xc00021c300)
	/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x257
net/http.HandlerFunc.ServeHTTP(0xc0044659a0?, {0x1292080?, 0xc00018e000?}, 0xc11cd0fa29bf03d9?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/go-openapi/runtime/middleware.SwaggerUI.func1({0x1292080, 0xc00018e000}, 0xc00021c300)
	/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/swaggerui.go:90 +0x271
net/http.HandlerFunc.ServeHTTP(0xc11cd0f2a9bdb8cd?, {0x1292080?, 0xc00018e000?}, 0x1000000ccc3b8?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/go-openapi/runtime/middleware.Spec.func1({0x1292080, 0xc00018e000}, 0x4d08e0?)
	/root/go/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x18c
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1292080?, 0xc00018e000?}, 0xc00367e800?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xc00020a480?}, {0x1292080, 0xc00018e000}, 0xc00021c300)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00012a320, {0x1292978, 0xc0035e3d70})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

The tool used to generate tcp sessions is [tcpkali](https://github.com/satori-com/tcpkali)

Run Server App - 
```
tcpkali -l8080 -T3h -v
```

Run Client App - 
```
tcpkali --connections 40000 -T 1000 --connect-rate=200 20.20.20.1:2020 --duration=6000

```

**Comment by PacketCrunch** [comment]
This was not reproduced. Closing this !!
